### ISSUE TITLE
Wrapping does not work when using Clang

### ISSUE THREAD

**Issue by ProfFan** [borglab/wrap#87]
Symptom:
```
Python 3.9.2 (default, Feb 20 2021, 18:40:11)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import state_estimation
>>> g = state_estimation.Greeting()
>>> g.getRot3()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: state_estimation.state_estimation.Greeting) -> gtsam::Rot3
>>>
```
and
```
Traceback (most recent call last):
  File "/home/fan/Projects/CV/SLAM/state-estimation/python/tests/test_example.py", line 29, in test_invertRot3
    g.invertRot3(r)
TypeError: invertRot3(): incompatible function arguments. The following argument types are supported:
    1. (self: state_estimation.state_estimation.Greeting, rot: gtsam::Rot3) -> gtsam::Rot3

Invoked with: <state_estimation.state_estimation.Greeting object at 0x7f88f02880b0>, R: [
        1, 0, 0;
        0, 1, 0;
        0, 0, 1
]
```

The cause is ~~unknown~~, but the following hypotheses are possible:
1. ~~the `typeinfo` weak symbol is not correctly resolved between modules~~
2. ~~libc++ uses pointer comparison, but GCC (libstdc++) uses string comparison when doing `dynamic_cast`. Obviously the string version is more robust.~~
3. ~~Bug in `pybind11`. We can try update to latest trunk and retry.~~
4. Using GCC to compile an extension when GTSAM is compiled with Clang. **Bad idea!**

**Comment by ProfFan** [comment]
Actual issue: microsoft/vscode-cmake-tools#1759

Be careful when you use VSCode - always check the actual command line!
